services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=phone_sinales_db'
      - 'POSTGRES_PASSWORD=KASQW$#$MNJF12431'
      - 'POSTGRES_USER=Sinales'
    ports:
      - '5001:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6001:6379'
